import enum
import pygame as pg


# Events für Event-Steuerung
class MyEvents(enum.IntEnum):
    EVENT_LOGGED_IN = pg.USEREVENT + 19
    EVENT_REGISTERED = pg.USEREVENT + 20
    EVENT_GAME_QUEUED  = pg.USEREVENT + 3
    EVENT_GAME_FOUND   = pg.USEREVENT + 4
    EVENT_SHIPS_POSTED = pg.USEREVENT + 5
    EVENT_GAME_STARTS  = pg.USEREVENT + 6
    EVENT_TURN_ARRIVED = pg.USEREVENT + 7
    EVENT_WAIT_4_TURN  = pg.USEREVENT + 8
    EVENT_TURN_POSTED  = pg.USEREVENT + 0
    #EVENT_STATISTICS   = pg.USEREVENT + 10
    EVENT_ALREADY_SHOT = pg.USEREVENT + 11
    EVENT_SERVER_ERROR = pg.USEREVENT + 12
    EVENT_REQUEST_ERROR = pg.USEREVENT + 13
    EVENT_OWN_TURN = pg.USEREVENT + 2
    EVENT_ENEMY_TURN = pg.USEREVENT + 1
    #EVENT_OWN_SUNK = pg.USEREVENT + 16
    #EVENT_ENEMY_SUNK = pg.USEREVENT + 14
    #EVENT_GAME_END = pg.USEREVENT + 15

